### ISSUE TITLE
Shortened processes names

### ISSUE THREAD

**Issue by aellwein** [rust-psutil/rust-psutil#86]
Please provide any of the following information if relevant:

- rust-psutil version: 3.1.0 (also reproducable with current master, "git+https://github.com/rust-psutil/rust-psutil#3dbb40fddee611c7bd80c2cf8dd2fec8b253caf0")
- target platform info
	- kernel version: MacOS Catalina 10.15.6
	- architecture: Darwin
	- (if linux) distro:
- any relevant hardware info: nothing special

While iterating through ``psutil::process::processes()``, the processes names are somehow shortened.
if pid and name are printed, i see only the starting parts, like "Google Chrome He" instead of "Google Chrome Helper"
and so on.

**Comment by cjbassi** [comment]
Can you give a minimal example? Also which field is it that's shrunk, `cmdline` or `name`?

**Comment by aellwein** [comment]
Sure! A simple example

```rust
fn main() {
    let ps_vec = psutil::process::processes().unwrap();
    for res in ps_vec {
        match res {
            Ok(ps) => println!("PID: {:?} NAME: {:?}", ps.pid(), ps.name().unwrap()),
            Err(_) => {}
        }
    }
}
```
this produces (excerpt):

```
PID: 33189 NAME: "psutil-rs"
PID: 33028 NAME: "MTLCompilerServi"
PID: 33027 NAME: "Activity Monitor"
PID: 32917 NAME: "Google Chrome He"
PID: 32912 NAME: "Google Chrome He"
PID: 32742 NAME: "Google Chrome He"
PID: 31838 NAME: "rust-analyzer-ma"
PID: 31833 NAME: "VSCodium Helper "
PID: 31785 NAME: "VSCodium Helper "
PID: 31783 NAME: "gitstatusd-darwi"
PID: 29975 NAME: "QuickLookUIServi"
PID: 28642 NAME: "VTDecoderXPCServ"
PID: 47726 NAME: "com.apple.CoreSi"
PID: 13694 NAME: "com.apple.WebKit"
PID: 9044 NAME: "MTLCompilerServi"
PID: 9043 NAME: "MTLCompilerServi"
PID: 25967 NAME: "com.apple.audio."
PID: 25934 NAME: "com.apple.audio."
PID: 21592 NAME: "recentsd"
PID: 15433 NAME: "IMAutomaticHisto"
PID: 15322 NAME: "AMPArtworkAgent"
PID: 15321 NAME: "com.apple.audio."
PID: 15320 NAME: "com.apple.BKAgen"
PID: 15319 NAME: "PodcastContentSe"
PID: 406 NAME: "QuickLookUIServi"
PID: 405 NAME: "backgroundtaskma"
PID: 402 NAME: "accountsd"
PID: 401 NAME: "rapportd"
PID: 377 NAME: "coreauthd"
PID: 190 NAME: "loginwindow"
```

BTW using cmdline() doesn't work at all:

```rust
fn main() {
    let ps_vec = psutil::process::processes().unwrap();
    for res in ps_vec {
        match res {
            Ok(ps) => println!("PID: {:?} NAME: {:?}", ps.pid(), ps.cmdline().unwrap()),
            Err(_) => {}
        }
    }
}
```
produces

```
thread 'main' panicked at 'not yet implemented', /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/psutil-3.2.0/src/process/sys/macos/process.rs:103:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: psutil::process::sys::macos::process::<impl psutil::process::process::Process>::sys_cmdline
   8: psutil::process::process::Process::cmdline
   9: psutil_rs::main
  10: std::rt::lang_start::{{closure}}
  11: std::rt::lang_start_internal
  12: std::rt::lang_start
  13: main
```

**Comment by cjbassi** [comment]
I tried the example on Linux and it seems to be working for me, so it must be a bug with the `name` method on macos.

**Comment by aellwein** [comment]
I just stumbled upon this issue:
https://github.com/heim-rs/heim/issues/262

**Comment by ColoursofOSINT** [comment]
This seems to be a mac os issue: 

computer@router ~ % ps aux | grep -i cold
computer         73870  66.7  0.3 416416960  75344   ??  S     3:51PM   0:00.82 /Applications/Cold Turkey Blocker.app/Contents/MacOS/Cold Turkey Blocker

But rust returns: 'Cold Turkey Bloc' (PID: 73870) which is 16 Characters 
 
or for TextThumbnailExtension

ps aux | grep -i TextThumbnailExtension
computer         63575   0.0  0.1 426997968  18288   ??  Ss   14May25   0:00.51 
/System/Library/ExtensionKit/Extensions/TextThumbnailExtension.appex/Contents/MacOS/TextThumbnailExtension

But again:
Checking for processes containing (case-insensitive): 'TextThumbnailExtension' ---
  No processes found containing 'TextThumbnailExtension'.

Checking for processes containing (case-insensitive): 'TextThumbnail' ---
  Potential match: 'TextThumbnailExt' (PID: 63575)

From the above code, with psutil = "5.2.0": 


PID: 58333 NAME: "SoftwareUpdateNo"
PID: 43219 NAME: "ControlCenterHel"
PID: 35336 NAME: "com.apple.WebKit"
PID: 35335 NAME: "WebThumbnailExte"
PID: 35334 NAME: "OfficeThumbnailE"
PID: 34527 NAME: "intelligenceplat"
PID: 34449 NAME: "generativeexperi"
PID: 34183 NAME: "AuthenticationSe"


and also for the second code block:

computer@router killer % RUST_BACKTRACE=1 cargo run

    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/killer`
thread 'main' panicked at /Users/computer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/psutil-5.2.0/src/process/sys/macos/process.rs:103:9:
not yet implemented
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
   2: core::panicking::panic
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:148:5
   3: psutil::process::sys::macos::process::<impl psutil::process::process::Process>::sys_cmdline
             at /Users/computer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/psutil-5.2.0/src/process/sys/macos/process.rs:103:3
   4: psutil::process::process::Process::cmdline
             at /Users/computer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/psutil-5.2.0/src/process/process.rs:69:3
   5: killer::main
             at ./src/main.rs:5:66
   6: core::ops::function::FnOnce::call_once
             at /Users/computer/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
