### ISSUE TITLE
cmdline panic - not yet implemented

### ISSUE THREAD

**Issue by Norgat** [rust-psutil/rust-psutil#91]
Hello,

I have problem with following code:

```
fn process_grabbler() {
  let processes = processes().unwrap();

  for proc in processes {
    match proc {      
      Ok(p) => {
        let path = p.cmdline()
                            .unwrap()
                            .unwrap_or_else(|| format!("[{}]", p.name().unwrap()));
        println!("{} {} {}", p.pid(), p.name().unwrap_or(String::from("-")), String::from("--"));
      },

      Err(_) => {}
    }
  }
}
```

but when I call `process_grabbler` I got this:

```
thread 'main' panicked at 'not yet implemented', /Users/norgat/.cargo/registry/src/github.com-1ecc6299db9ec823/psutil-3.2.0/src/process/sys/macos/process.rs:103:9
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/norgat/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:521:12
   1: psutil::process::sys::macos::process::<impl psutil::process::process::Process>::sys_cmdline
             at /Users/norgat/.cargo/registry/src/github.com-1ecc6299db9ec823/psutil-3.2.0/src/process/sys/macos/process.rs:103:3
   2: psutil::process::process::Process::cmdline
             at /Users/norgat/.cargo/registry/src/github.com-1ecc6299db9ec823/psutil-3.2.0/src/process/process.rs:70:3
   3: fireman::process_grabbler
             at ./src/main.rs:30:20
   4: fireman::main
             at ./src/main.rs:42:3
   5: core::ops::function::FnOnce::call_once
             at /Users/norgat/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

What I miss? Don't see difference with https://github.com/rust-psutil/rust-psutil/blob/fc02ac17b3efcb2554fb6502f2174b46c0380535/examples/ps.rs

PS I use Mac Mini M1

**Comment by cjbassi** [comment]
The `cmdline` method isn't implemented yet on macOS:

https://github.com/rust-psutil/rust-psutil/blob/fc02ac17b3efcb2554fb6502f2174b46c0380535/src/process/sys/macos/process.rs#L102-L104
